name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - mkdocs.yml
      - README.md
      - '.github/workflows/publish-docs.yaml'

  release:
    types:
      - published

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          sparse-checkout: docs

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --break-system-packages \
            mike==2.1.3 \
            mkdocs-material==9.6.22 \
            mkdocs-include-markdown-plugin==7.2.0 \
            mkdocs-awesome-pages-plugin==2.10.1

      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: mike deploy main
        if: contains(github.ref, 'refs/heads/main')
        run: |
          mike deploy --push main

      - name: mike deploy new version
        if: contains(github.ref, 'refs/tags/v') && !github.event.release.prerelease
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          mike deploy --push --update-aliases "${VERSION}" latest
